#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn prettier --write . && git add .
# Данный хук был добавлен следующей командой: npx husky add .husky/pre-commit "yarn prettier --write . && git add ."
